name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn generate:protobufs
      - run: yarn run build
